project_id = "intaj-platform"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://intaj.nabih.tech", "https://www.intaj.nabih.tech"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false

[auth.email.smtp]
host = "smtp.gmail.com"
port = 587
user = "env(SMTP_USER)"
pass = "env(SMTP_PASS)"
admin_email = "admin@intaj.com"
sender_name = "Intaj Platform"

[auth.email.template.invite]
subject = "Welcome to Intaj - Complete Your Account Setup"

[auth.email.template.confirmation]
subject = "Confirm Your Intaj Account"

[auth.email.template.recovery]
subject = "Reset Your Intaj Password"

[auth.email.template.email_change]
subject = "Confirm Your New Email Address"

[storage]
enabled = true
file_size_limit = "50MiB"
